### ISSUE TITLE
Day 2 Configurations

### ISSUE THREAD

**Issue by ryanpei** [pivotal-cf/docs-pcf-gsg#12]
I believe most customers have to setup their LBs/domains/etc. on Day 1 (even before they deploy PCF). Day 2 is probably not the right designation.

User Auth/Accounts, especially for Ops Mgr, is probably also a Day 1 concern.

**Comment by mlimonczenko** [comment]
Hi @ryanpei,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
