### ISSUE TITLE
customizing/config_firewall does not make sense to me

### ISSUE THREAD

**Issue by ryanpei** [pivotal-cf/docs-pcf-gsg#14]
I may be missing the right context, but when I read through the instructions for customizing/config_firewall.html I do not understand what I am supposed to do with this information. There is a list of ports to be open (but where?), and then some instructions about updating iptables. Where do I run these updates?

The last section of the document is probably needed in a different section; keep in mind this is the first page of "Deploying Bosh and Ops Manager", and this section assumes you have Ops Mgr already deployed.

**Comment by mlimonczenko** [comment]
Hello @ryanpei,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
