### ISSUE TITLE
PAS Administrator is usually given a tool to aid their workflows

### ISSUE THREAD

**Issue by ryanpei** [pivotal-cf/docs-pcf-gsg#15]
In most PCF Platform Dojos, we give customers an (unsupported) tool called cf-mgmt - https://github.com/pivotalservices/cf-mgmt. This allows for a PAS/ERT Admin to manage all their cf metadata (orgs, spaces, users, routes, quotas, ASGs, etc.) via a self-service model where app dev teams submit PRs which are then accepted/rejected by the Admin.

We should at least mention the availability of this tool and how to use it, since so many of our customers use it today.

**Comment by mlimonczenko** [comment]
Hi @ryanpei,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
