### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by AmberAlston** [pivotal-cf/docs-pcf-gsg#17]
On page https://docs.pivotal.io/pivotalcf/2-0/installing/highlights.html - "Operators can additionally use the NSX Manager to configure policies for PCF applications. See the NSX-T Container Plug-in for Kubernetes and Cloud Foundry - Installation and Administration Guide for more information." The link to https://s3.amazonaws.com/prod.tracker2/resource/85792716/nsxt_21_ncp_kubernetes-1127.pdf is broken.

**Comment by seviet** [comment]
Thanks, @AmberAlston! Fixed
