### ISSUE TITLE
Why is this page called: Architecture and Installation Overview

### ISSUE THREAD

**Issue by tjeppesen** [pivotal-cf/docs-pcf-gsg#22]
There is no architecture overview on this page nor the referenced links even though the title hints at that. It would be good to have that overview somewhere though or a link to it if it should not be maintained in the docs.

**Comment by pspinrad** [comment]
Thanks @tjeppesen -- good point, we need to rework the whole install and architecture section to be clearer and more of a standalone guide-- for now, made the link to Reference Architectures more prominent https://github.com/pivotal-cf/docs-pcf-gsg/commit/d56a9cc566888d5a79c7f775636790589c613472.
